language: java
addons:
  sonarcloud:
    organization: lofhjann
    token:
      secure: MyZso2uHNzG/LH6Qvl6RBN4MlQrLT0u/0XGFU7ZlL+Ak/Nx1fUvu3F6JDn6qdmK/BiPyOpbGsXeu8tSVh25UjE0luOEcC9kPurfUJA4fRys15RvWo5I5Iy2sqE7QhmmfezOigv5C80JjOwOHmg5i/c0qlTs5vYZvDKjJvvFrtndWPlQtcpOS4Ypk1cAERm7D6rGMdAG0ffLtROmuayl04m6EIawsfMZ4BjlfDMF10eDIz3gWaidUcBhG8PqhtLIEPPZKgHXbqJS1Y9pvs/aNQV2wZrNh+xBCfRVjaMW1WgEumhiuoQI/ffX/1ti7vp+RqTSy9oOdAec30CV2mr8E1Q7KL8CBjPR9V1tAFAWyYIQqDgtMCzujTg9rP0t668JKbAfWBay6KsTHavBq2vLftjM2+zf20gpoJl65uOBE/IlqUiYHDcDXbj6LNVfGUxTU5bAQO0+kq2CJY8vl5eoDnGqiInfX3P61ns0UdPrHICnJVwmFTrGvWBpGCXXNTQDGCfr+wijMiEB/9K6JipbBBKUHMJ9ZVB0wCaxHKXaIGMz1/8YSkcKCIcWTXvu34HAtilXXR2bcpGnjtiWQ3mWWIPBF/xZOKuyPlhBmoM6v5JVrVzbyDtmaHXTigS00upMBvn4cZacJ+Bo5aJPVx48c5n5enkIspOtdPnEX2b2IA1A=
script:
  - ./gradlew jacocoTestReport sonarqube
after_success:
- bash <(curl -s https://codecov.io/bash)
